apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: devops-module3
spec:
  interval: 3m
  chart:
    spec:
      chart: mongodb
      version: 16.5.6 # https://artifacthub.io/packages/helm/bitnami/mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    auth:
      rootPassword: 0yCQVo8llCD93iU
      username: tung
      password: XOQCG4RP1L5Dpzy
      database: devops-training
    persistence:
      enabled: true
      size: 3Gi 